name: CN HW2 CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest # Uses GitHub's runner with Docker pre-installed

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js Environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install Dependencies
              run: npm ci

            - name: Run Tests
              run: npm run test
